version: 2
#orbs:
#  hello: circleci/hello-build@0.0.7
#workflows:
#  "Hello Workflow":
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
